### ISSUE TITLE
A dependency of the surge package was vandalized

### ISSUE THREAD

**Issue by briantist** [ansible-community/github-docs-build#12]
See:
- https://github.com/sintaxi/surge/issues/469
- https://github.com/Marak/colors.js/issues/285

This makes surge useless at the moment, but looking at the offending commit, it's not actually dangerous: https://github.com/Marak/colors.js/commit/074a0f8ed0c31c35d13d28632bd8a049ff136fb6#diff-92bbac9a308cd5fcf9db165841f2d90ce981baddcb2b1e26cfff170929af3bd1R18 just runs an infinite loop.

Note that the surge workflow drops all permissions except for `contents: read`, so it has no access to change anything it runs in, and can't read anything sensitive except the surge token passed into the workflow.

**Comment by DABH** [comment]
Please just pin the colors dependency to 1.4.0, and see the following if you need additional context: https://github.com/Marak/colors.js/issues/285#issuecomment-1008212640
