### ISSUE TITLE
GitHub Actions: Deprecating save-state and set-output commands

### ISSUE THREAD

**Issue by tremble** [ansible-community/github-docs-build#56]
Looking at the output of one of a recent docs validation run for amazon.aws I'm seeing:

```
 Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
```

It would appear that there's something that needs to change...

**Comment by felixfontein** [comment]
According to https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-output-parameter, it should be rather easy to replace.

**Comment by felixfontein** [comment]
I tried this out in #57.
