### ISSUE TITLE
CI failures looking for `antsibull-docs<3,>=2`

### ISSUE THREAD

**Issue by briantist** [ansible-community/github-docs-build#69]
CI is failing a bunch of tests because it seems to be trying to install a version of `antisbull-docs` that doesn't exist yet. I'm not sure yet where it's getting that range from.

https://github.com/ansible-community/github-docs-build/actions/runs/4922546028/jobs/8793437859#step:4:366

cc @felixfontein if you have any ideas

**Comment by felixfontein** [comment]
@briantist you are installing antsibull-docs from its `main` branch; the sphinx-init subcommand creates a requirements.txt with that version range: https://github.com/ansible-community/antsibull-docs/blob/main/src/antsibull_docs/data/sphinx_init/requirements_txt.j2#L5

This also means that if you use that subcommand of the 2.0.0a1 release, then it generates a requirements.txt that cannot be used (until 2.0.0 itself is released).

CC @gotmax23 should we do a 2.0.0a2 to fix this, or simply wait a bit and release 2.0.0?

**Comment by gotmax23** [comment]
I think this warrants a hotfix antsibull-docs release.

**Comment by felixfontein** [comment]
I restarted the tests once 2.0.0a2 was out, and now they pass: https://github.com/ansible-community/github-docs-build/actions/runs/4922546028

**Comment by briantist** [comment]
thanks very much @felixfontein !
